### ISSUE TITLE
O que é MVC?

### ISSUE THREAD

**Issue by joannestephany** [Ericles-Porty/SalesWebMVC#8]
### Discussed in https://github.com/Ericles-Porty/SalesWebMVC/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **joannestephany** July 13, 2022</sup>
Não consegui compreender o conceito do projeto</div>

**Comment by Ericles-Porty** [comment]
MVC Significa Model View Control. A model é responsável pela estrutura dos objetos, a view é responsável por toda visualização do sistema e a control faz o controle das requisições.
